# Generated by Django 4.2.10 on 2024-02-07 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('abn', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('abn_status_and_date', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=255)),
                ('legal_name', models.CharField(max_length=255)),
                ('main_business_location', models.CharField(max_length=255)),
                ('acn_arbn', models.CharField(max_length=255)),
                ('gst_status_and_registration_date', models.CharField(max_length=255)),
                ('deductible_gift_recipient_status_and_dates', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TradingName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_names', to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_names', to='business.business')),
            ],
        ),
    ]
